"""add booking audit fields and reasons

Revision ID: 2668742fca5c
Revises: 6fd2a8548ba8
Create Date: 2026-02-28 11:35:45.782818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2668742fca5c'
down_revision: Union[str, Sequence[str], None] = '6fd2a8548ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_reason', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_reserved_event_date'), 'bookings', ['event_date'], unique=True, postgresql_where="((status)::text = 'RESERVED'::text)")
    op.drop_column('bookings', 'cancellation_reason')
    op.drop_column('bookings', 'rejection_reason')
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'rejected_at')
    op.drop_column('bookings', 'approved_at')
    # ### end Alembic commands ###
